GET_TABLES_AND_COLUMNS = """
SELECT
    t.TABLE_NAME,
    c.COLUMN_NAME,
FROM
    INFORMATION_SCHEMA.TABLES AS t
JOIN
    INFORMATION_SCHEMA.COLUMNS AS c ON t.TABLE_NAME = c.TABLE_NAME
    AND t.TABLE_SCHEMA = c.TABLE_SCHEMA
WHERE
    t.TABLE_TYPE = 'BASE TABLE' AND t.TABLE_SCHEMA = %s
ORDER BY
    t.TABLE_NAME, c.ORDINAL_POSITION;
"""


GET_TABLES_AND_COLUMNS_WITH_DATA = """
SELECT
    t.TABLE_NAME,
    c.COLUMN_NAME,
    c.DATA_TYPE,
    c.CHARACTER_MAXIMUM_LENGTH,
    c.IS_NULLABLE,
    CASE WHEN kcu.CONSTRAINT_NAME IS NOT NULL THEN 'YES' ELSE 'NO' END AS IS_UNIQUE
FROM
    INFORMATION_SCHEMA.TABLES AS t
JOIN
    INFORMATION_SCHEMA.COLUMNS AS c ON t.TABLE_NAME = c.TABLE_NAME
    AND t.TABLE_SCHEMA = c.TABLE_SCHEMA
LEFT JOIN
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS kcu ON c.TABLE_NAME = kcu.TABLE_NAME
    AND c.COLUMN_NAME = kcu.COLUMN_NAME AND c.TABLE_SCHEMA = kcu.TABLE_SCHEMA
    AND kcu.CONSTRAINT_NAME = 'UNIQUE'
WHERE
    t.TABLE_TYPE = 'BASE TABLE' AND t.TABLE_SCHEMA = %s
ORDER BY
    t.TABLE_NAME, c.ORDINAL_POSITION;
"""


GET_REFERENCES = """
SELECT
    CONSTRAINT_NAME,
    TABLE_NAME AS ParentTable,
    REFERENCED_TABLE_NAME AS ReferencedTable,
    COLUMN_NAME AS ParentColumn,
    REFERENCED_COLUMN_NAME AS ReferencedColumn
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
    REFERENCED_TABLE_NAME IS NOT NULL AND TABLE_SCHEMA = %s
ORDER BY
    ParentTable, ReferencedTable;
"""


GET_INDEXES = """
SELECT
    TABLE_NAME AS TableName,
    INDEX_NAME AS IndexName,
    COLUMN_NAME AS ColumnName
FROM
    INFORMATION_SCHEMA.STATISTICS
WHERE
    TABLE_SCHEMA = %s
ORDER BY
    TABLE_NAME, INDEX_NAME, SEQ_IN_INDEX;
"""


GET_STORED_PROCEDURES = """
SELECT
    ROUTINE_NAME,
    ROUTINE_TYPE,
    CREATED,
    LAST_ALTERED
FROM
    INFORMATION_SCHEMA.ROUTINES
WHERE
    ROUTINE_TYPE IN ('PROCEDURE', 'FUNCTION')
    AND ROUTINE_SCHEMA = %s;

"""


GET_VIEWS = """
SELECT
    TABLE_NAME AS ViewName,
    VIEW_DEFINITION
FROM
    INFORMATION_SCHEMA.VIEWS
WHERE
    TABLE_SCHEMA = %s;
"""


GET_PRIMARY_KEYS = """
SELECT
    TABLE_NAME AS TableName,
    COLUMN_NAME AS ColumnName
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
    CONSTRAINT_NAME = 'PRIMARY' AND TABLE_SCHEMA = %s;
"""
